version: '3.9'
services:
  banking-api:
    container_name: banking-api
    image: oscaralmgren/rest-banking-api-go-tutorial:0.23
    # environment:
    #   - BANKING_API=v1
    ports:
      - "3000:3000"
    networks:
      - backend
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7.40-debian
    ports: 
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql:rw
      - ./initdb:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=oscar-camp-tutorial
    networks:
      - backend
  mongo:
    image: mongo:6.0.4-jammy
    container_name: mongodb-banking
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: oscar-camp-tutorial
    networks:
      - backend    
volumes:
  mysqldata:
    driver: local
networks:
  backend:
    name: "banking-backend"