apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-api
spec:
  selector:
    matchLabels:
      app: banking-api
  template:
    metadata:
      labels:
        app: banking-api
    spec:
      containers:
      - name: banking-api
        image: oscaralmgren/rest-banking-api-go-tutorial:0.22
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
